theme: jekyll-theme-minimal

title: Ethical Visualization in the Age of Big Data
tagline: A Planning Workshop Summary
description: A planning workshop to seek interdisciplinary expert perspectives on ethically and visually representing the historical place of misrepresented peoples and locales.
test: Extra content
show_downloads: false
